version: "3"

services:
  broker-mqtt-service-mng:
    image: eclipse-mosquitto
    ports:
      - "9001:9001"
      - "1883:1883"
    volumes:
      - LAB_MQTT:/mosquitto/data            
  store-mongo-service-mng:
    image: mongo:4.2
    ports:
      - "27017:27017"
    environment: 
        - storageEngine=wiredTiger
    volumes: 
      - LAB_MONGO:/data/db
volumes: 
  LAB_MQTT:
  LAB_MONGO: